# HYPERPARAMS
import pickle as pkl

SEED = 1
LOG_DIR = 'Run/Logging'
MODEL_NAME = 'modelv1.1'
DATA_DIR = 'Data/preprocessed_data/paired_self_supervised'
LOG_STEPS = 10
LEARNING_RATE = 1e-3
Z_DIM = 128
LOSS_RATIO = 1000
NUM_TRAINER_WORKERS = 1
NUM_DATA_WORKERS = 8
BATCH_SIZE = 128
FIND_UNUSED=False
USE_GPU = 'cpu'
NUM_EPOCHS = 300
SAMPLE_ECG_PKL = 'sample_ecg.pkl'
SAVE_N_STEPS = 1000

with open(SAMPLE_ECG_PKL, 'rb') as f:
    SAMPLE_ECG = pkl.load(f)

NUM_BLOCKS = (8,8,8)
NUM_STRIDES = (4,6,4,2)
NUM_KERNELS = (8,8,8,4)
DECODER_KERNELS = (7,8,8,6)
DECODER_STRIDES = (4,4,4,4)
NUM_PLANES = (16, 64, 128)
assert len(NUM_PLANES) == len(NUM_BLOCKS)
START_CHANNELS = 1
PEAK_WINDOW = 5
PEAK_SIGMA = 1
PEAK_MASK_LOSS_FACTOR = 2
FIX_FECG_ALPHA = 3
SWITCH_FECG_WINDOW_ALPHA = 1
SWITCH_FECG_ALPHA = -1

DROP_LAST = False
RATIO = 4
SDV = 0.5
LOAD_INTO_MEMORY = False
NUM_MECG_RANDS = 10
NUM_FECG_RANDS = 20